### ISSUE TITLE
REQUEST: Migrate aws/karpenter-core

### ISSUE THREAD

**Issue by jonathan-innis** [kubernetes/org#4562]
### New repo, staging repo, or migrate existing

Migrate existing

### Is it a staging repo?

no

### Requested name for new repository

karpenter

### Which Organization should it reside

kubernetes-sigs

### Who should have admin access?

mwielgus, maciekpytel, gjtempleton, ~etarn~, ellistarn, jonathan-innis, tzneal, bwagner5, njtran

### Who should have write access?

N/A

### Who should be listed as approvers in OWNERS?

mwielgus, maciekpytel, gjtempleton, ~etarn~, ellistarn, jonathan-innis, tzneal, bwagner5, njtran

### Who should be listed in SECURITY_CONTACTS?

jonathan-innis, etarn, njtran, tzneal

### What should the repo description be?

Karpenter is a Kubernetes Node Lifecycle Management Solution built for flexibility, performance, and simplicity.

### What SIG and subproject does this fall under?

sig-autoscaling

### Please provide references to appropriate approval for this new repo

Approval from SIG chair (@gjtempleton) after lazy consensus period here: https://github.com/kubernetes/org/issues/4258#issuecomment-1784253306

Awaiting approval from @mwielgus and then we have a go-ahead on this move.

### Additional context for request

We're staging out a final release prior to the repo move (`v0.32.0`) which should be completed today or tomorrow. After that point, we have the forward momentum to begin removing the repo to have the next release (`v0.33.0`) be released from the `kubernetes-sigs` organization.

We'd like to see the `OWNERS`, `OWNERS_ALIASES`, and `SECURITY_CONTACTS.md` files look like this

`OWNERS` file

```
# See the OWNERS docs: https://git.k8s.io/community/contributors/guide/owners.md

approvers:
  - sig-autoscaling-leads
  - karpenter-maintainers

reviewers:
  - karpenter-reviewers
```

`OWNERS_ALIASES` file

```
# See the OWNERS_ALIASES docs: https://git.k8s.io/community/contributors/guide/owners.md#owners_aliases

aliases:
  sig-autoscaling-leads:
    - mwielgus
    - maciekpytel
    - gjtempleton
  karpenter-maintainers:
    - ellistarn
    - jonathan-innis
    - tzneal
    - bwagner5
    - njtran
  karpenter-reviewers:
    - jackfrancis
    - tallaxes
```

`SECURITY_CONTACTS` file

```
# Defined below are the security contacts for this repo.
#
# They are the contact point for the Security Response Committee to reach out
# to for triaging and handling of incoming issues.
#
# The below names agree to abide by the
# [Embargo Policy](https://git.k8s.io/security/private-distributors-list.md#embargo-policy)
# and will be removed and replaced if they violate that agreement.
#
# DO NOT REPORT SECURITY VULNERABILITIES DIRECTLY TO THESE NAMES, FOLLOW THE
# INSTRUCTIONS AT https://kubernetes.io/security/

jonathan-innis
ellistarn
njtran
tzneal
```
